export default {
  // Organizations based actions
  GET_ALL_ORGANIZATIONS: 'GET_ALL_ORGANIZATIONS',
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  GET_ORGANIZATION: 'GET_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION_BY_ID: 'DELETE_ORGANIZATION_BY_ID',
  // Employees based actions
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  GET_ALL_EMPLOYEES: 'GET_ALL_EMPLOYEES',
  GET_ALL_EMPLOYEES_BY_ORG: 'GET_ALL_EMPLOYEES_BY_ORG',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  DELETE_EMPLOYEE_BY_ID: 'DELETE_EMPLOYEE_BY_ID',
  GET_EMPLOYEES_BY_SALARY: 'GET_EMPLOYEES_BY_SALARY',
};
